syntax on
set tabstop=4
set shiftwidth=4
set expandtab
set number
set incsearch
set ignorecase
set hlsearch
set showmatch
set t_Co=256
set termguicolors

call plug#begin()

Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-file.vim'
Plug 'arcticicestudio/nord-vim'

call plug#end()

nnoremap <silent> <Space> :NERDTreeToggle<CR>
nnoremap <silent> <Space>h :hori :belowright :terminal<CR>
nnoremap <silent> <Space>v :vert :botright :terminal<CR>
colorscheme nord

